Reporting_Assistant_New/Controllers/MyIssuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reporting_Assistant_New.ViewModel;
using Reporting_Assistant_New.Models;
using Reporting_Assistant_New.Identity;
using System.Collections;
using System.IO;

namespace Reporting_Assistant_New.Controllers
{
    public class MyIssuesController : Controller
    {
        ReportingDbContext db = new ReportingDbContext();
        ApplicationDbContext userDb = new ApplicationDbContext();
        CommonDataController cdc = new CommonDataController();
        // GET: /Admin/MyIssues/
        public ActionResult Issues()
        {
            dropdown();
            String UserId = Convert.ToString(Session["UserId"]);
            if(UserId==null)
            {
                return RedirectToAction("Account", "Logout");
            }
            else
            {
                List<Task> List = new List<Task>();
                List<TaskDone> tdoneList = new List<TaskDone>();
                List<FinalComments> fcmntlist = new List<FinalComments>();
                TaskDone alldata = new TaskDone();
                Task Lstdata = new Task();
                DateTime fromdate = Convert.ToDateTime(System.DateTime.Now.AddDays(-1).ToString("dd/MMM/yyyy"));
                DateTime todate = Convert.ToDateTime(System.DateTime.Now.ToString("dd/MMM/yyyy") + " 23:59");
                if (UserId != null)
                {
                    //var data = (from t in db.Task
                    //join user in userDb.Users on t.AdminUserId equals user.Id where(t.UserId==UserId && user.Id==UserId)
                    //select new { t.Description, t.Screen, user.UserName }).ToList();
                    //var data = db.Task.Join(userDb.Users, p => p.AdminUserId == UserId, pc => pc.Id == UserId, (p, pc) => new { p.Screen, p.Description, pc.UserName }).ToList(); ;
                    var data = db.Task.Where(m => m.UserId == UserId && m.DOT >= fromdate && m.DOT <= todate).ToList();
                    foreach (var item in data)
                    {
                        var admin_name = userDb.Users.Where(m => m.Id == item.AdminUserId).Select(m => m.UserName).FirstOrDefault();
                        var obj = new Task();
                        obj.Screen = item.Screen;
                        obj.Description = item.Description;
                        obj.UserId = admin_name;
                        obj.DOT = item.DOT;
                        List.Add(obj);
                    }
                    var tdone = db.TaskDone.Where(m => m.UserId == UserId && m.DOTD >= fromdate && m.DOTD <= todate).ToList();
                    foreach (var item in tdone)
                    {
                        var tddata = new TaskDone();
                        tddata.Screen = item.Screen;
                        tddata.Projects = item.Projects;
                        tddata.ProjectId = item.ProjectId;
                        tddata.ImageAttached = item.ImageAttached;
                        tddata.DOTD = item.DOTD;
                        tddata.Description = item.Description;
                        tdoneList.Add(tddata);

                    }
                    var fcomments = db.FinalComment.Where(m => m.UserId == UserId && m.DOFC >= fromdate && m.DOFC <= todate).ToList();
                    foreach (var item in fcomments)
                    {
                        var admin_name = userDb.Users.Where(m => m.Id == item.AdminUserId).Select(m => m.UserName).FirstOrDefault();
                        var fcdata = new FinalComments();
                        fcdata.Screen = item.Screen;
                        fcdata.Projects = item.Projects;
                        fcdata.ProjectId = item.ProjectId;
                        fcdata.ImageAttached = item.ImageAttached;
                        fcdata.AdminUserId = admin_name;
                        fcdata.DOFC = item.DOFC;
                        fcdata.Description = item.Description;
                        fcmntlist.Add(fcdata);

                    }
                    //string AdminuserId = data[0].AdminUserId.ToString();
                    //foreach (var item in TaskList)
                    //{
                    //    var UserName = userDb.Users.Where(m => m.Id == item.AdminUserId.ToString()).ToList();
                    //    AdminNamelist.Add(UserName);
                    //    ViewBag.AdminNameList = AdminNamelist;
                    //}

                    alldata.tlist = List.ToList();
                    alldata.tdlist = tdoneList.ToList();
                    alldata.fclist = fcmntlist.ToList();
                }
                return View(alldata);

            }

            
        }
        public void dropdown()
        {
            List<SelectListItem> ProjectList = new List<SelectListItem>();
            var pr_data = db.Project.OrderBy(a => a.ProjectName).Select(m => new { m.ProjectId, m.ProjectName }).ToList();
            if (pr_data.Count > 0)
            {

                foreach (var Value in pr_data)
                {
                    ProjectList.Add(new SelectListItem { Text = Value.ProjectName, Value = Value.ProjectId.ToString() });


                }
                ViewBag.pr_data = ProjectList;
            }
        }

        [HttpPost]
        public ActionResult Insertd_data(TaskDone tddata, HttpPostedFileBase BaseImg)
        {
           if(ModelState.IsValid) 
           {
                
              string userid = Convert.ToString(Session["UserId"]);

                try
                {
                    if (tddata.ProjectId.ToString() != "" && userid != "")
                    {
                        string path = uploadImage(BaseImg);
                        var data = db.TaskDone.Create();
                        try
                        {
                            data.ProjectId = tddata.ProjectId;
                            data.Screen = tddata.Screen;
                            data.UserId = userid;
                            data.Description = tddata.Description;
                            data.DOTD = DateTime.Now;
                            data.ImageAttached = path;
                            db.TaskDone.Add(data);
                            db.SaveChanges();
                            TempData["Message"] = cdc.Success("The data saved successfully!");
                            return RedirectToAction("Issues");
                            //var data2 = new { status = "Success", message = "Data Added Successfully!!" };
                            //return Json(data2, JsonRequestBehavior.AllowGet);
                        }
                        catch (Exception ex)
                        {
                            //var data2 = new { status = "fail", message = "Please try after some time!!" };
                            //return Json(data2, JsonRequestBehavior.AllowGet);
                            TempData["Message"] = cdc.Success("Some Issue Appeared!");
                            return RedirectToAction("Issues");
                        }
                    }
                    else
                    {
                        TempData["Message"] = cdc.Success("Some Issue Appeared!");
                        return RedirectToAction("Issues");
                    }
                }
                catch (Exception ex)
                {
                    TempData["Message"] = cdc.Success("Some Issue Appeared!");
                    return RedirectToAction("Issues");
                }
            }
           else
           {
               TempData["Message"] = cdc.Success("Some Issue Appeared!");
               return RedirectToAction("Issues");
           }
        }

        [NonAction]
        public string uploadImage(HttpPostedFileBase ImageAttached)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (ImageAttached != null && ImageAttached.ContentLength > 0)
            {
                string extension = Path.GetExtension(ImageAttached.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png") || extension.ToLower().Equals(".gif"))
                {
                    try
                    {
                        path = Path.Combine(Server.MapPath("~/Content/UploadImage"), random + Path.GetFileName(ImageAttached.FileName));
                        ImageAttached.SaveAs(path);
                        path = "~/Content/UploadImage/" + random + Path.GetFileName(ImageAttached.FileName);
                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('Only jpg, jpeg, pg and jif files are allowed')</script>");
                }
            }
            else
            {
                Response.Write("<script>alert('Please Select a file')</script>");
            }

            return path;
        }
        
    }
}

Reporting_Assistant_New/Views/MyIssues/Issues.cshtml
@model Reporting_Assistant_New.ViewModel.TaskDone
@{
    ViewBag.Title = "Issues";
    Layout = "~/Views/Shared/_LayoutPageGeneral.cshtml";
}


<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="~/Scripts/DataTables/js/dataTables.bootstrap4.min.js"></script>
<link href="~/Scripts/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<style>
    .collapsible {
        background-color: #777;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
    }

        .active, .collapsible:hover {
            background-color: #555;
        }

    .content {
        padding: 0 18px;
        display: none;
        overflow: hidden;
        background-color: #f1f1f1;
    }
</style>
<h2>Issues</h2>

@using (Html.BeginForm("Insertd_data", "MyIssues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<button type="button" class="collapsible">@DateTime.Now.AddDays(-1).DayOfWeek,@DateTime.Now.AddDays(-1).ToString("dd/MMM/yyyy")</button>
<div class="content">
    <button type="button" class="collapsible">Tasks Assigned</button>
    <div class="content">
        @if (Model.tlist.Count != 0 && Model.tlist[0].DOT == DateTime.Today.AddDays(-1))
        {
            foreach (var i in Model.tlist)
            {
            
                <div class="col-lg-4 col-md-4 col-sm-4 bootstrap-touchspin-down bootstrap-select">
                    <button type="button" class="collapsible ">@(i.UserId == null && i.DOT == DateTime.Today.AddDays(-1) ? "" : i.DOT == DateTime.Today.AddDays(-1) ? i.UserId : "")</button>
                    <div class="content advance-table-row table-bordered" style="border-color:blue">
                        @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
                        <fieldset>
                            <legend>@(i.Screen == null ? "" : i.DOT == DateTime.Today.AddDays(-1) ? i.Screen : "")</legend>
                            <h3>@(i.Description == null ? "" : i.DOT == DateTime.Today.AddDays(-1) ? i.Description : "")</h3>
                        </fieldset>
                    </div>
                </div>
            }
        }
        else if (Model.tlist.Count == 0)
        {
                <p style="color:red">No Task Assigned</p>
        }
        else
        {
                    <p style="color:red">No Task Assigned</p>
        }
        
    </div>
    
    <button type="button" class="collapsible">Task Done</button>
    <div class="col-lg-12 col-md-12 col-sm-12 bootstrap-touchspin-down">
    @if (Model.tdlist.Count != 0 && Model.tdlist[0].DOTD == DateTime.Today.AddDays(-1))
    {
        foreach (var i in Model.tdlist)
        {

            <div class="container-fluid advance-table-row table-bordered bootstrap-touchspin-up" style="border-color:green">
               <fieldset>
                    <legend>@(i.Screen == null ? "" : i.DOTD == DateTime.Today.AddDays(-1) ? i.Screen : "")</legend>
                    <h3>@(i.Description == null ? "" : i.DOTD == DateTime.Today.AddDays(-1) ? i.Description : "")</h3>
                </fieldset>
            </div>

        }
    }
    else if (Model.tdlist.Count == 0)
    {
                     <p style="color:red">No Task Done</p>
    }

    else
    {
                    <p style="color:red">No Task Done</p>
    }

        @*<lebel style="color:red">New Task Done</lebel>*@

        @*<div class="container-fluid advance-table-row table-bordered bootstrap-touchspin-up" style="border-color:green" id="tddata_div">qua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
            @*<fieldset>
                <legend class="col-lg-6 col-md-6 col-sm-6 bootstrap-touchspin-down">Project Name @Html.DropDownListFor(m => m.ProjectId, new SelectList(ViewBag.pr_data, "Value", "Text"), "---select---", new { @class = "form-control" })*@
               @*@Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Description"})
                        @Html.TextBoxFor(m => m.Screen, new { @class = "form-control", placeholder = "Screen Name" })*@
                    @*<button class="btn btn-success" type="submit" id="submit">Submit </button>
                </legend>
            </fieldset>
        </div>*@
    </div>
   
    <button type="button" class="collapsible">Final Comment</button>
    <div class="content">
@if (Model.fclist.Count != 0 && Model.fclist[0].DOFC == DateTime.Today.AddDays(-1))
{
        @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
    foreach (var i in Model.fclist)
    {

            <div class="col-lg-4 col-md-4 col-sm-4 bootstrap-touchspin-down bootstrap-select">
                <button type="button" class="collapsible ">@(i.AdminUserId == null ? "" : i.DOFC == DateTime.Today.AddDays(-1) ? i.AdminUserId : "")</button>
                <div class="content advance-table-row table-bordered" style="border-color:blue">
                    @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
                    <fieldset>
                        <legend>@(i.Screen == null ? "" : i.DOFC == DateTime.Today.AddDays(-1) ? i.Screen : "")</legend>
                        <h3>@(i.Description == null ? "" : i.DOFC == DateTime.Today.AddDays(-1) ? i.Description : "")</h3>
                    </fieldset>
                </div>
            </div>
    }
}
else if (Model.fclist.Count == 0)
{
            <p style="color:red">No Final Comment Found</p>
}
else
{
            <p style="color:red">No Final Comment Found</p>
}
    </div>
</div>


<button type="button" class="collapsible">@DateTime.Now.DayOfWeek,@DateTime.Now.ToString("dd/MMM/yyyy")</button>
<div class="content">
    <button type="button" class="collapsible">Tasks Assigned</button>
    <div class="content">
        @if (Model.tlist.Count != 0 && Model.tlist[0].DOT == DateTime.Today.AddDays(-0))
        {
            foreach (var i in Model.tlist)
            {
            
                <div class="col-lg-4 col-md-4 col-sm-4 bootstrap-touchspin-down bootstrap-select">
                    <button type="button" class="collapsible ">@(i.UserId == null ? "" : i.DOT == DateTime.Today ? i.UserId : "")</button>
                    <div class="content advance-table-row table-bordered" style="border-color:blue">
                        @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
                        <fieldset>
                            <legend>@(i.Screen == null ? "" : i.DOT == DateTime.Today ? i.Screen : "")</legend>
                            <h3>@(i.Description == null ? "" : i.DOT == DateTime.Today ? i.Description : "")</h3>
                        </fieldset>
                    </div>
                </div>
            }
        }
        else if (Model.tlist.Count == 0)
        {
            <p style="color:red">No Task Assigned</p>
        }
        else
        {
            <p style="color:red">No Task Assigned</p>
        }
        
    </div>
    
    <button type="button" class="collapsible">Task Done</button>
    <div class="col-lg-12 col-md-12 col-sm-12 bootstrap-touchspin-down">
@if (Model.tdlist.Count != 0 && Model.tdlist[0].DOTD == DateTime.Today.AddDays(-0))
{
    foreach (var i in Model.tdlist)
    {
             <div class="container-fluid advance-table-row table-bordered bootstrap-touchspin-up" style="border-color:green">
                <fieldset>
                    <legend>@(i.Screen == null ? "" : i.DOTD == DateTime.Today ? i.Screen : "")</legend>
                    <h3>@(i.Description == null ? "" : i.DOTD == DateTime.Today ? i.Description : "")</h3>
                </fieldset>
            </div>

    }
}
else if (Model.tdlist.Count == 0)
{
            <p style="color:red">No Task Done</p>
}
else
{
            <p style="color:red">No Task Done</p>
}

        <lebel style="color:red">New Task Done</lebel>

        <div class="container-fluid advance-table-row table-bordered bootstrap-touchspin-up" style="border-color:green" id="tddata_div">
            @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
            <fieldset>
                <legend class="col-lg-6 col-md-6 col-sm-6 bootstrap-touchspin-down">Project Name @Html.DropDownListFor(m => m.ProjectId, new SelectList(ViewBag.pr_data, "Value", "Text"), "---select---", new { @class = "form-control" })
               @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Description" })
                        @Html.TextBoxFor(m => m.Screen, new { @class = "form-control", placeholder = "Screen Name" })
                    <label for="image">Image</label>
                    <input type="file" class="form-control-file" id="image" name="BaseImg" />
                    <button class="btn btn-success" type="submit" id="submit">Submit </button>
                </legend>
            </fieldset>
        </div>
    </div>
    <button type="button" class="collapsible">Final Comment</button>
    <div class="content">
        @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
        @if (Model.fclist.Count != 0 && Model.fclist[0].DOFC == DateTime.Today.AddDays(-0))
        {
            foreach (var i in Model.fclist)
            {
             <div class="col-lg-4 col-md-4 col-sm-4 bootstrap-touchspin-down bootstrap-select">
                <button type="button" class="collapsible ">@(i.AdminUserId == null ? "" : i.DOFC == DateTime.Today ? i.AdminUserId : "")</button>
                <div class="content advance-table-row table-bordered" style="border-color:blue">
                    @*<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>*@
                    <fieldset>
                        <legend>@(i.Screen == null ? "" : i.DOFC == DateTime.Today ? i.Screen : "")</legend>
                        <h3>@(i.Description == null ? "" : i.DOFC == DateTime.Today ? i.Description : "")</h3>
                    </fieldset>
                </div>
            </div>
            }
        }
        else if (Model.fclist.Count == 0)
        {
            <p style="color:red">No Task Done</p>
        }
        else
        {
            <p style="color:red">No Task Done</p>
        }
    </div>
</div>

}

@Html.ValidationSummary()
@Html.Raw(TempData["Message"])
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
    function fxsave_tskdn_data(ProjectId, Description, Screen) {
        if (ProjectId!=""|| null)
        {
            //alert("jjj")
            var getData = { id: ProjectId, Des: Description,Screen:Screen };
           $.ajax({
                type: "POST",
                url: '@Url.Action("Insertd_data", "MyIssues")',
                data2: getData,
                dataType: "json",
                success: function (data2) {
                    alert("jjj")
                    if (data2.status == "success") {
                        $("#success").html("<div class='alert alert-success alert-dismissable'><i class='fa fa-info-circle fa-fw'></i><button class='close' aria-hidden='true' data-dismiss='alert' type='button'>×</button>" + data2.message + "</div>");
                        $("#Loder").modal('hide');
                    }

                    else {
                        $("#warning").html("<div class='alert alert-danger alert-dismissable'><i class='fa fa-info-circle fa-fw'></i><button class='close' aria-hidden='true' data-dismiss='alert' type='button'>×</button>" + data2.message + "</div>");
                        $("#Loder").modal('hide');
                    }
                }


            });
        }
    }
</script>