Reporting_Assistant_New/Areas/Admin/Controllers/UserDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Filters;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.UI.WebControls;
using Microsoft.Owin.Security;
using Reporting_Assistant_New.Identity;
using Reporting_Assistant_New.ViewModel;
using System.IO;
using System.Security.Cryptography;
using System.Configuration;
using Reporting_Assistant_New.Controllers;
using Reporting_Assistant_New.Areas.ViewModels;
using Reporting_Assistant_New.Models;


namespace Reporting_Assistant_New.Areas.Admin.Controllers
{
    public class UserDetailController : Controller
    {
        //
        // GET: /Administrator/UserDetails/

        CommonDataController cdc = new CommonDataController();
        //[MyActionFilter]
        //[MyResultFilter]
        //[MyExceptionFilter]
        public ActionResult UserDetails()
        {
            List<uduser> listdata = new List<uduser>();
            ApplicationDbContext db = new ApplicationDbContext();
            var data = db.Users.ToList();
            foreach (var item in data)
            {
                var userdata = new uduser();
                userdata.userid = item.Id;
                userdata.Username = item.UserName;
                userdata.Mobile = item.PhoneNumber;
                userdata.DateOfBirth = item.Birthday;
                userdata.Address = item.Address;
                userdata.Email = item.Email;
                userdata.BaseImg = item.UserImg;
                listdata.Add(userdata);
            }
            return View(listdata);
        }



        public ActionResult UserDetailsEdit(string ids)
        {
            var appdbcontext = new ApplicationDbContext();
            var userstore = new ApplicationUserStore(appdbcontext);
            var userManager = new ApplicationManagercs(userstore);

            var data = appdbcontext.Users.Where(m => m.Id == ids).ToList();

            uduser model = new uduser();
            model.userid = data[0].Id;
            model.Username = data[0].UserName;
            model.Address = data[0].Address;
            model.BaseImg = data[0].UserImg;
            model.City = data[0].city;
            model.Email = data[0].Email;
            model.Country = data[0].country;
            model.DateOfBirth = data[0].Birthday;
            model.Mobile = data[0].PhoneNumber;
            return View(model);

        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserDetailsEdit(uduser data, HttpPostedFileBase BaseImg)
        {
            if (ModelState.IsValid)
            {

                var db = new ApplicationDbContext();
                var userstore = new ApplicationUserStore(db);
                var userManager = new ApplicationManagercs(userstore);

                string path = uploadImage(BaseImg);
                if(path!=null)
                {
                    ApplicationUser databaseData = db.Users.Where(m => m.Id == data.userid).FirstOrDefault();
                    databaseData.Email = data.Email;
                    databaseData.UserName = data.Username;
                    databaseData.PhoneNumber = data.Mobile;
                    databaseData.Address = data.Address;
                    databaseData.city = data.City;
                    databaseData.country = data.Country;
                    databaseData.Birthday = data.DateOfBirth;
                    databaseData.UserImg = path;
                    db.SaveChanges();
                    TempData["Message"] = cdc.Success("Details Updated Successfully");
                    return RedirectToAction("UserDetails");
                }
                else
                {
                    TempData["Message"] = cdc.Warning("Please Select a Image");
                    return View();
                }
                
            }
            else
            {
                ModelState.AddModelError("My error", "Invalid data");
                return View();
            }
        }

        public string uploadImage(HttpPostedFileBase BaseImg)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if (BaseImg != null && BaseImg.ContentLength > 0)
            {
                string extension = Path.GetExtension(BaseImg.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png") || extension.ToLower().Equals(".gif"))
                {
                    try
                    {
                        path = Path.Combine(Server.MapPath("~/Content/UploadImage"), random + Path.GetFileName(BaseImg.FileName));
                        BaseImg.SaveAs(path);
                        path = "~/Content/UploadImage/" + random + Path.GetFileName(BaseImg.FileName);
                    }
                    catch (Exception ex)
                    {
                        path = "-1";
                    }
                }
                else
                {
                    Response.Write("<script>alert('Only jpg, jpeg, pg and jif files are allowed')</script>");
                }
            }
            else
            {
                path = "-1";
                TempData["Message"] = cdc.Success("Please Select a Image");
            }

            return path;
        }

        //public string saveImage(string BaseImg)
        //{
        //    string filename = Guid.NewGuid().ToString() + ".jpg";
        //    System.Drawing.Image ImgFile = cdc.Base64ToImage(BaseImg);
        //    var path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Content/UploadedFile/"), filename);
        //    ImgFile.Save(path, System.Drawing.Imaging.ImageFormat.Jpeg);
        //    return filename;
        //}
    }
}

Reporting_Assistant_New/Areas/Admin/Views/UserDetail/UserDetails.cshtml
@model List<Reporting_Assistant_New.Areas.ViewModels.uduser>
@{
    ViewBag.Title = "UserDetails";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageForAdmin.cshtml";
}

<style>
    .dataTables-example{
        border-color:blue;
    }
</style>
<script src="~/JS/MyHeader.js"></script>
@using (Html.BeginForm("UserDetails", "UserDetail", new { area = "Admin" }, FormMethod.Post, new { encrypt = "multipart/form-data" }))
{
    <div id="constrain">
        <div class="container-fluid">
            <div class="row">
                @Html.Raw(TempData["Message"])

                <div class="col-md-12">
                    <div class="white-box">
                        <div class="form-group">
                        </div>
                        <h3 class="box">User Details</h3>
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Images</th>
                                        <th>User Name</th>
                                        <th>Email</th>
                                        <th>Mobile Number</th>
                                        <th>Date Of Birth</th>
                                        <th>Address</th>
                                        <th>Operations</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var o in Model)
                                    {
                                        <tr>
                                            <td>
                                                <img style="max-height:100px; max-width:100px; padding-left:10px" src="@Url.Content(@o.BaseImg)" alt="">
                                            </td>
                                            @*<td><input type="checkbox" name="ids" id="ids" value="@o.Email" /> </td>*@
                                            <td>@(o.Username == null ? "" : o.Username)</td>
                                            <td>@(o.Email == null ? "" : o.Email)</td>
                                            <td class="custom-th">@(o.Mobile == null ? "" : o.Mobile)</td>
                                            <td>@(o.DateOfBirth == null ? "" : o.DateOfBirth.Value.ToShortDateString())</td>
                                            <td>@(o.Address == null ? "" : o.Address)</td>
                                            @*<td class="custom-th">
                                                    @{if (o.isActive == true)
                                                    {
                                                        <span style="color:green">Active</span>
                                                    }
                                                    else if (o.isActive == false)
                                                    {
                                                        <span style="color:red">In-Active</span>
                                                    }
                                                    }
                                                </td>*@
                                            <td>
                                            <a class="btn btn-info" href="~/Admin/UserDetail/UserDetailsEdit?ids=@o.userid">Edit</a>
                                                <span id="confirmDeleteSpan_@o.userid" style="display:none">
                                                    <span>Are You sure you want to delete?</span>
                                                    <button type="submit" class="btn btn-danger"> Yes </button>
                                                    <button type="#" class="btn btn-primary" onclick="confirmDelete('@o.userid', false)"> No </button>
                                                </span>
                                                <span id="deletespan_@o.userid">
                                                    <a href="#" class="btn btn-danger" onclick="confirmDelete('@o.userid', true)"> Delete </a>
                                                </span>
                                            </td>
                                        </tr>
                                    }

                                </tbody>

                            </table>
                            @Html.ValidationSummary()
                            @Html.Raw(TempData["Message"])
                            @section  Scripts{
                                <script src="~/JS/DeleteScript.js"></script>
                            }
                            <script src="~/Scripts/jquery-1.10.2.min.js"></script>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@Html.ValidationSummary()
@Html.Raw(TempData["Message"])

Reporting_Assistant_New/Areas/Admin/Views/UserDetail/UserDetailsEdit.cshtml
@model Reporting_Assistant_New.Areas.ViewModels.uduser
@{
    ViewBag.Title = "UserDetailsEdit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageForAdmin.cshtml";
}

<h2>UserDetailsEdit</h2>
<style>
    #DateOfBirth {
        width: 4000px;
        height: 40px;
        border: solid;
        border-color: lightgray;
    }
</style>
<script src="~/JS/MyHeader.js"></script>
<form action="~/Admin/UserDetail/UserDetailsEdit" method="post" enctype="multipart/form-data">
@*@using (Html.BeginForm("UserDetailsEdit", "UserDetail", new { area = "Admin" }, FormMethod.Post, new { encrypt = "multipart/form-data" }))
{*@ 
    @Html.AntiForgeryToken()

    <div class="form-row">
        @Html.Raw(TempData["Message"])
        @Html.HiddenFor(m => m.userid)
        <div class="row">
            <div class="form-group col-md-12 col-sm-12 col-md-12">
                <div class="row">
                    <div class="form-group col-md-4 col-sm-4 col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Username)
                            @Html.TextBoxFor(m => m.Username, new { placeholder = "Username", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Username)
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.DateOfBirth)<br />
                            @*@Html.TextBoxFor(m => m.DateOfBirth, "{0:d}", new { placeholder = "Please type Date Of Birth In a form of dd/mm/yyyy", @class = "form-control" })*@
                            @Html.EditorFor(m => m.DateOfBirth, "{0:d}", new { id = "DateOfBirth", placeholder = "Please type Date Of Birth In a form of dd/mm/yyyy", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.DateOfBirth)
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Email)
                            @Html.TextBoxFor(m => m.Email, new { placeholder = "Email", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Mobile)
                            @Html.TextBoxFor(m => m.Mobile, new { placeholder = "Enter Mobile Number", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Mobile)
                        </div>
                    </div>

                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Address)
                            @Html.TextBoxFor(m => m.Address, new { placeholder = "Enter Full Address", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Address)
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.City)
                            @Html.TextBoxFor(m => m.City, new { placeholder = "City", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.City)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Country)
                            @Html.TextBoxFor(m => m.Country, new { placeholder = "Country", @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Country)
                        </div>
                    </div>
                    <div class="form-group col-md-4 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label class="control-label">Signature Image</label>
                            @if (Model.BaseImg != "")
                            {
                                <br />
                                
                                 <img style="max-height:100px; max-width:100px; padding-left:10px" src="@Url.Content(@Model.BaseImg)" alt="">
                                <br />
                            }
                            <br />
                            <label for="image">Image</label>
                            <input type="file" class="form-control-file" id="image" name="BaseImg" />
                        </div>
                    </div>
                </div>
            </div>
            @Html.ValidationSummary()
        </div>
        <div class="row">
            <div class="form-group col-md-12 col-sm-12 col-md-12">
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="ViewAll" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>                     @*}*@
</form>